"use client";

import { useEffect } from "react";
import { useRouter } from "next/navigation";

const POLL_INTERVAL_MS = 2500;

// A rejected group's replacement is generated by a background job — this
// polls just the first id in the group (the reject action's atomic guarded
// update plus the replacement job's single-transaction persist together
// guarantee every id in a group is always in lockstep, so one is enough).
// Deliberately not JobInterstitial — that's now a full-screen, page-blocking
// overlay for whole-plan generation; this is a small, scoped card update.
export function RegeneratingCard({
  cropName,
  varietyName,
  statusUrl,
}: {
  cropName: string;
  varietyName: string | null;
  statusUrl: string;
}) {
  const router = useRouter();

  useEffect(() => {
    const pollTimer = setInterval(async () => {
      try {
        const res = await fetch(statusUrl, { cache: "no-store" });
        if (!res.ok) return;
        const data = (await res.json()) as { status: string };
        if (data.status !== "regenerating") {
          router.refresh();
        }
      } catch {
        // transient network error — the next poll will retry
      }
    }, POLL_INTERVAL_MS);
    return () => clearInterval(pollTimer);
  }, [statusUrl, router]);

  return (
    <div className="flex flex-col items-center gap-2 rounded-lg border border-black/10 bg-white p-6 shadow-card text-center">
      <span className="motion-safe:animate-[grow-pulse_1.8s_ease-in-out_infinite] text-3xl" aria-hidden>
        🌱
      </span>
      <p className="text-sm font-medium">
        Finding an alternative for {cropName}
        {varietyName ? ` (${varietyName})` : ""}…
      </p>
    </div>
  );
}
