export const MAX_DAILY_GROW_PLAN_GENERATIONS = 3;
export const MAX_RECOMMENDATION_REGENERATIONS = 5;
export const MAX_DAILY_PLANT_DIAGNOSES = 5;
export const MAX_DAILY_GROWING_AREA_ESTIMATIONS = 3;
export const MAX_ESTIMATION_PHOTOS = 5;
